//! DNS configuration utilities

use log::{info, warn};
use std::fs;
use std::net::Ipv4Addr;
use std::path::Path;

const RESOLV_HEADER: &str = "# Generated by DHCP client\n";

/// Apply DNS configuration by updating interface-specific resolv.conf
pub async fn apply_dns_config(dns_servers: &[Ipv4Addr], domain_name: Option<&str>, interface_name: &str) -> Result<(), Box<dyn std::error::Error>> {
    // Create interface-specific paths
    let interface_dir = format!("/tmp/minis/etc/netns/{}", interface_name);
    let resolv_path = format!("{}/resolv.conf", interface_dir);
    let backup_path = format!("{}/resolv.conf.dhcp-backup", interface_dir);
    
    // Create directory if it doesn't exist
    fs::create_dir_all(&interface_dir)?;

    // Backup existing resolv.conf if it exists and no backup exists yet
    if Path::new(&resolv_path).exists() && !Path::new(&backup_path).exists() {
        if let Err(e) = fs::copy(&resolv_path, &backup_path) {
            warn!("Failed to backup existing resolv.conf: {}", e);
        }
    }

    // Build new resolv.conf content
    let mut content = String::new();
    content.push_str(RESOLV_HEADER);

    // Add domain if provided with interface comment
    if let Some(domain) = domain_name {
        content.push_str(&format!("search {} # {}\n", domain, interface_name));
    }

    // Add nameservers with interface comment
    for dns_server in dns_servers {
        content.push_str(&format!("nameserver {} # {}\n", dns_server, interface_name));
    }

    // Write new resolv.conf
    match fs::write(&resolv_path, content) {
        Ok(()) => {
            info!("📝 Updated {} with {} DNS servers", resolv_path, dns_servers.len());
            if let Some(domain) = domain_name {
                info!("📝 Set domain to: {}", domain);
            }
            Ok(())
        }
        Err(e) => {
            // Try to restore backup if write failed
            if Path::new(&backup_path).exists() {
                if let Err(restore_err) = fs::copy(&backup_path, &resolv_path) {
                    warn!("Failed to restore resolv.conf backup: {}", restore_err);
                }
            }
            Err(format!("Failed to write {}: {}", resolv_path, e).into())
        }
    }
}

/// Restore original DNS configuration from backup
pub async fn restore_dns_config(interface_name: &str) -> Result<(), Box<dyn std::error::Error>> {
    let interface_dir = format!("/tmp/minis/etc/netns/{}", interface_name);
    let resolv_path = format!("{}/resolv.conf", interface_dir);
    let backup_path = format!("{}/resolv.conf.dhcp-backup", interface_dir);

    if Path::new(&backup_path).exists() {
        fs::copy(&backup_path, &resolv_path)?;
        fs::remove_file(&backup_path)?;
        info!("📝 Restored original resolv.conf from backup for interface {}", interface_name);
        Ok(())
    } else {
        // No backup exists, just remove DHCP-generated file
        if Path::new(&resolv_path).exists() {
            let content = fs::read_to_string(&resolv_path)?;
            if content.starts_with(RESOLV_HEADER) {
                fs::remove_file(&resolv_path)?;
                info!("📝 Removed DHCP-generated resolv.conf for interface {}", interface_name);
            }
        }
        Ok(())
    }
}