//! DNS configuration utilities.
//!
//! Supports IPv4 and IPv6 nameservers. The caller supplies the full
//! `resolv.conf` path; this module never assumes `/etc/resolv.conf`. Per the
//! split-file model, the v4 client typically writes `<path>.ipv4` and the v6
//! client writes `<path>.ipv6`; merging is the orchestrator's responsibility.

use log::info;
use std::fs;
use std::net::IpAddr;
use std::path::{Path, PathBuf};

const RESOLV_HEADER_PREFIX: &str = "# Generated by rust-dhcp";

fn backup_path(resolv_conf_path: &Path) -> PathBuf {
    let mut s = resolv_conf_path.as_os_str().to_os_string();
    s.push(".dhcp-backup");
    PathBuf::from(s)
}

/// Apply DNS configuration by writing to `resolv_conf_path`.
///
/// `family_tag` is written into the header comment ("v4" or "v6") for
/// diagnostics. `nameservers` accepts both `Ipv4Addr` and `Ipv6Addr` via
/// `IpAddr`.
pub async fn apply_dns_config(
    resolv_conf_path: &Path, nameservers: &[IpAddr], domain_name: Option<&str>, search_domains: &[String], family_tag: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    if let Some(parent) = resolv_conf_path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent)?;
        }
    }

    let backup = backup_path(resolv_conf_path);
    if resolv_conf_path.exists() && !backup.exists() {
        if let Ok(existing) = fs::read_to_string(resolv_conf_path) {
            if !existing.starts_with(RESOLV_HEADER_PREFIX) {
                let _ = fs::copy(resolv_conf_path, &backup);
            }
        }
    }

    let mut content = String::new();
    content.push_str(&format!("{} ({})\n", RESOLV_HEADER_PREFIX, family_tag));

    if let Some(domain) = domain_name {
        content.push_str(&format!("domain {}\n", domain));
    }
    if !search_domains.is_empty() {
        content.push_str("search ");
        for (i, d) in search_domains.iter().enumerate() {
            if i > 0 {
                content.push(' ');
            }
            content.push_str(d);
        }
        content.push('\n');
    } else if let Some(domain) = domain_name {
        content.push_str(&format!("search {}\n", domain));
    }

    for ns in nameservers {
        content.push_str(&format!("nameserver {}\n", ns));
    }

    fs::write(resolv_conf_path, content)?;
    info!(
        "📝 Wrote {} nameservers to {} ({})",
        nameservers.len(),
        resolv_conf_path.display(),
        family_tag
    );
    Ok(())
}

/// Restore the original resolv.conf at `resolv_conf_path` if a backup exists,
/// or remove the file if it was generated by us.
pub async fn restore_dns_config(resolv_conf_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let backup = backup_path(resolv_conf_path);
    if backup.exists() {
        fs::copy(&backup, resolv_conf_path)?;
        fs::remove_file(&backup)?;
        info!("📝 Restored {} from backup", resolv_conf_path.display());
        return Ok(());
    }
    if resolv_conf_path.exists() {
        if let Ok(content) = fs::read_to_string(resolv_conf_path) {
            if content.starts_with(RESOLV_HEADER_PREFIX) {
                fs::remove_file(resolv_conf_path)?;
                info!("📝 Removed DHCP-generated {}", resolv_conf_path.display());
            }
        }
    }
    Ok(())
}
