//! The trait user must implement to provide a persistent lease storage for the DHCP server.

use std::net::Ipv4Addr;

use lease::Lease;

/// Errors generated by the `Storage` trait methods.
#[derive(thiserror::Error, Debug)]
pub enum Error {
    #[error("Client getting error: {0}")]
    GetClient(String),
    #[error("Client adding error: {0}")]
    AddClient(String),
    #[error("Client deleting error: {0}")]
    DeleteClient(String),

    #[error("Lease getting error: {0}")]
    GetLease(String),
    #[error("Lease adding error: {0}")]
    AddLease(String),
    #[error("Lease updating error: {0}")]
    UpdateLease(String),

    #[error("Frozen address checking error: {0}")]
    CheckFrozen(String),
    #[error("Frozen address adding error: {0}")]
    AddFrozen(String),

    #[error("Another error: {0}")]
    Other(String),
}

/// Must be implemented by the DHCP server crate user.
///
/// Be sure your storage is `ACID`.
pub trait Storage
where
    Self: Sync + Send,
{
    /// Must return the client ID if the client is associated with the given address.
    ///
    /// # Errors
    /// Must return `Error::GetClient(desc)` if there is a database I/O error
    /// or `Error::Other(desc)` on another error.
    fn get_client(&self, address: &Ipv4Addr) -> Result<Option<Vec<u8>>, Error>;

    /// Must associate the client with the given address.
    ///
    /// # Errors
    /// Must return `Error::AddClient(desc)` if there is a database I/O error
    /// or `Error::Other(desc)` on another error.
    fn add_client(&mut self, address: &Ipv4Addr, client_id: &[u8]) -> Result<(), Error>;

    /// Must disassociate the client ID from the given address.
    ///
    /// # Errors
    /// Must return `Error::DeleteClient(desc)` if there is a database I/O error
    /// or `Error::Other(desc)` on another error.
    fn delete_client(&mut self, address: &Ipv4Addr) -> Result<(), Error>;

    /// Must return the address lease of the given client if the lease exists.
    ///
    /// # Errors
    /// Must return `Error::GetLease(desc)` if there is a database I/O error
    /// or `Error::Other(desc)` on another error.
    fn get_lease(&self, client_id: &[u8]) -> Result<Option<Lease>, Error>;

    /// Must associate the client ID with the given lease.
    ///
    /// # Errors
    /// Must return `Error::AddLease(desc)` if there is a database I/O error
    /// or `Error::Other(desc)` on another error.
    fn add_lease(&mut self, client_id: &[u8], lease: Lease) -> Result<(), Error>;

    /// Must update the lease associated with the given client ID if the lease exists.
    ///
    /// # Errors
    /// Must return `Error::UpdateLease(desc)` if there is a database I/O error
    /// or `Error::Other(desc)` on another error.
    fn update_lease(
        &mut self,
        client_id: &[u8],
        action: &mut FnMut(&mut Lease) -> (),
    ) -> Result<(), Error>;

    /// Must return `true` if the given address has been frozen, `false` otherwise.
    ///
    /// # Errors
    /// Must return `Error::CheckFrozen(desc)` if there is a database I/O error
    /// or `Error::Other(desc)` on another error.
    fn check_frozen(&self, address: &Ipv4Addr) -> Result<bool, Error>;

    /// Must mark the address as frozen due to a client `DHCPDECLINE` report.
    ///
    /// # Errors
    /// Must return `Error::AddFrozen(desc)` if there is a database I/O error
    /// or `Error::Other(desc)` on another error.
    fn add_frozen(&mut self, address: &Ipv4Addr) -> Result<(), Error>;
}
